### ISSUE TITLE
Stuck at http://pathway.theodi.org/assessments/45

### ISSUE THREAD

**Issue by jacattell** [theodi/ODMAT#277]
When I get to http://pathway.theodi.org/assessments/45 I receive the following error message:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by ldodds** [comment]
Hi,

The fix for this should be released tomorrow morning.

I will update the issue afterwards so you can retest if possible?

Thanks,

L

On Thursday, May 28, 2015, James Arthur Cattell <notifications@github.com>
wrote:

> When I get to http://pathway.theodi.org/assessments/45 I receive the
> following error message:
>
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/ODMAT/issues/277>.
>


-- 
Leigh Dodds, Senior Consultant, theODI.org
@ldodds
The ODI, 65 Clifton Street, London EC2A 4JE

**Comment by ldodds** [comment]
@jacattell I just pushed out a fix that was causing failure to correctly load some incomplete assessments. Could you retest and let me know if you can now view your assessment?

**Comment by jacattell** [comment]
Yeap, its working now. Thanks for fixing
